version: '3'
services:
  node-exporter:
    image: prom/node-exporter
    container_name: dzhai-node-exporter
    network_mode: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.textfile.directory=/etc/node-exporter/
    restart: unless-stopped
  prometheus:
    image: prom/prometheus
    container_name: dzhai-prometheus
    network_mode: host
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped